=== kurtraschke/comp-hist/scripts/xml/comp-hist.dtd
<!--comp-hist.dtd-->
<!ELEMENT tree (node)+>
<!ELEMENT node (id, name, date, type, status) (reference, link, info)+ >
<!ELEMENT id  (#PCDATA)>
<!ELEMENT name  (#PCDATA)>
<!ELEMENT reference  (#PCDATA)>
<!ELEMENT info  (#PCDATA)>
<!ELEMENT date     (EMPTY)>
<!ATTLIST date     year   CDATA #REQUIRED
                   month       CDATA "01"
                   day         CDATA "01"
                   hour        CDATA "01"
                   minute      CDATA "00">
<!ELEMENT type  (EMPTY)>
<!ATTLIST type types (os|hardware|announcement|language) #REQUIRED>
<!ELEMENT status  (EMPTY)>
<!ATTLIST status status (released|internal|prototype|research|contevol) #REQUIRED>
<!ELEMENT link (id)+>
<!ATTLIST link linktype (aka|successor|codetaken|influenced|runson|writtenin) #REQUIRED>

=== kurtraschke/comp-hist/scripts/xml/demo.xml
<?xml version="1.0"?>
<!DOCTYPE TREE PUBLIC "" "http://comp-hist.sourceforge.net/comp-hist.dtd">
<tree>
<node>
<id>test</id>
<name>Test Node</name>
<date year="2000" month="1" day="1" hour="0" minute="01" />
<type types="os" />
<status status="released" />
<reference>reference</reference>
<info>All of your info goes here.</info>
</node>

<node>
<id>test2</id>
<name>Test Node 2</name>
<date year="2000" month="1" day="1" hour="0" minute="01" />
<type types="os" />
<status status="released" />
<reference>reference</reference>
<info>All of your info goes here.</info>
<link linktype="aka">id</link>
</node>
</tree>
